#!/usr/bin/env python3
"""adapt_project.py —— rx-sweep 适配脚本（方式 A：固化包装器 rx_runner.py）

把用户的 OFDM 接收机训练工程适配成可批量实验：
  1. 扫 --project-root 找 train.py（或用 --train-py 指定）。
  2. Read train.py，确认它 import utils/ 下的训练脚本，打印训练脚本路径。
  3. 生成 <project-root>/rx_runner.py 包装器，接受
     --model/--kd/--teacher-ckpt/--epochs/--gpu，把 --model 透传到
     rx_models.get_model(model, RxConfig)，并在载入模型后打印 [RX-GATE] 行。
  4. 其余训练逻辑（loss/optim/data/eval）回调用户原脚本——模板里以明确标记的
     <<<TODO>>> 插入点示意，由适配 agent / 用户按实际脚本结构接线（adaptation-guide
     方式 B 兜底）。

不重写用户训练逻辑；幂等（重跑覆盖，旧版 .bak）；fail loud。

契约：reference/contracts.md §3（GATE 格式）+ §5（脚本 CLI）。
      reference/adaptation-guide.md（方式 A 包装器）。

纯 stdlib，不依赖 orca —— 脚本在用户工程上跑，可能没装 orca。
"""

import argparse
import os
import re
import shutil
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# train.py 中 utils/ 训练脚本 import 的识别模式
#   命中以下任一形态（module-name 捕获在 group 1）：
#     from utils        import <name>      group(2) = <name>
#     from utils.<sub>  import <name>      group(1) = <sub>
#     from utils        import <name> as X group(2) = <name>
#     import utils.<sub>                   group(1) = <sub>
#     import utils.<sub> as X              group(1) = <sub>
# ---------------------------------------------------------------------------
_UTILS_IMPORT_RE = re.compile(
    r'^\s*(?:'
    r'from\s+utils(?:\.(\w+))?\s+import\s+(\w+)'
    r'|'
    r'import\s+utils(?:\.(\w+))?'
    r')',
    re.MULTILINE,
)

# rx_runner.py 模板。用 __TOKEN__ 占位（避免与模板内 Python 花括号/f-string 冲突）。
# <<<TODO>>> 标记处是用户/适配 agent 的插入点（adaptation-guide 方式 B 兜底）。
_RUNNER_TEMPLATE = '''#!/usr/bin/env python3
"""rx_runner.py —— rx-sweep 适配包装器（auto-generated by adapt_project.py）

接受 --model/--kd/--teacher-ckpt/--epochs/--gpu，用 rx_models.get_model(name, RxConfig)
实例化模型并打印 [RX-GATE] 行；其余训练逻辑回调用户原脚本（loss/optim/data/eval 不动）。

带 <<<TODO>>> 标记的段是插入点，由适配 agent 按你的 utils/ 训练脚本结构接线；
重跑 adapt_project.py 会覆盖本文件（旧版备份为 rx_runner.py.bak）。

契约：reference/contracts.md §3（GATE 格式）。
"""
import argparse
import os
import sys

# 让 import 能同时找到工程根 + rx_sweep_models/（adapt 阶段拷进去的 rx_models 包）。
# 包名重定向：源 orca/.../models/rx_models/ → 工程内 rx_sweep_models/rx_models/，
# 故把 rx_sweep_models/ 加进 sys.path 后 `import rx_models` 即可解。
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
sys.path.insert(0, os.path.join(_HERE, "rx_sweep_models"))

import torch

# 用户训练脚本（auto-detected by adapt_project.py）
__USER_TRAIN_IMPORT__

# rx_models 包由 adapt 阶段从 orca/skills/rx-sweep/scripts/models/rx_models/ 整包
# 拷进 rx_sweep_models/（见 SKILL.md 阶段 1）。
from rx_models import get_model, RxConfig


def _fmt_shape(s):
    """[1,4,48,32,1] -> '[1,4,48,32,1]'（无空格逗号分隔）。

    gate_check._parse_kv 按空格切 token，list str 化默认带空格（'[1, 4, ...]'）会让
    io_in 被截成 '[1,'，导致 io_in mismatch 误报（B1）。
    """
    return "[" + ",".join(str(int(x)) for x in s) + "]"


def _gate_line(model, cfg, io_in, io_out, passed):
    """打印一行 [RX-GATE] key=val ...（contracts.md §3 格式，无空格逗号）。

    维度全从 cfg 读（M4：单一真相源）——P/F/S/blocks/embed 一份 cfg，GATE 行与
    get_model 共享，杜绝硬编码维度漂移（原 pure_cnn_model 64/32 bug 的根治点）。
    """
    fields = [
        f"model={model}",
        f"P={cfg.num_ports}",
        f"F={cfg.num_subcarriers}",
        f"S={cfg.num_symbols}",
        f"blocks={cfg.num_blocks}",
        f"embed={cfg.embed_dim}",
        f"io_in={_fmt_shape(io_in)}",
        f"io_out={_fmt_shape(io_out)}",
        f"gate={'PASS' if passed else 'FAIL'}",
    ]
    print("[RX-GATE] " + " ".join(fields), flush=True)


def _smoke_and_gate(args):
    """建模型 + dummy 前向 smoke + 打 GATE 行。返回 (model, cfg, passed)。"""
    # === 维度 cfg 构造点（单一真相源）===
    # <<<TODO: 用户微调>>> 默认 RxConfig(num_symbols=32, ...)；若用户工程有 cfg 对象
    #         （如 utils.train_rx.cfg / 顶层 config.py 的实例），适配 agent 在此注入，
    #         根治维度漂移：
    #         from <user_module> import cfg as _user_cfg   # 或 utils.__USER_TRAIN_MODULE__.cfg
    #         cfg = RxConfig.from_project_cfg(_user_cfg)
    cfg = RxConfig()

    # === 模型实例化点 ===
    # <<<TODO: 用户微调>>> 若用户脚本模型实例化点非标准（深嵌 / 多分支 / 多模型），
    #         按 adaptation-guide 方式 B 在 utils/<训练脚本>.py 里改实例化点：
    #         from rx_models import get_model, RxConfig
    #         model = get_model(args.model, cfg)
    model = get_model(args.model, cfg)
    model.eval()

    # dummy 前向 smoke（I/O 对齐 rx_models 全方案：cfg.io_shape = [1,P,F,S,1]）
    shape = tuple(cfg.io_shape)
    x = torch.zeros(shape, dtype=torch.float32)
    io_in = list(shape)
    io_out = []
    passed = False
    try:
        with torch.no_grad():
            y = model(x)
        io_in = list(x.shape)
        io_out = list(y.shape)
        passed = (io_in == cfg.io_shape and io_out == cfg.io_shape)
    except Exception as e:  # noqa: BLE001 —— smoke 失败不致命，GATE 报 FAIL
        print(f"[RX-GATE] forward smoke crashed: {e!r}",
              file=sys.stderr, flush=True)

    # GATE 行用同一份 cfg（M4：避免 GATE 硬编码与 get_model 脱节）
    _gate_line(args.model, cfg, io_in, io_out, passed)
    return model, cfg, passed


def main():
    parser = argparse.ArgumentParser(description="rx-sweep 适配包装器")
    parser.add_argument("--model", default="pure_cnn",
                        help="rx_models 方案名（model8_trf / pure_cnn / cnn_trf_alt / "
                             "feat_complex / feat_diff / feat_fft / feat_adjbeam），"
                             "默认 pure_cnn")
    parser.add_argument("--kd", action="store_true",
                        help="启用蒸馏（需 --teacher-ckpt）")
    parser.add_argument("--teacher-ckpt", default=None,
                        help="teacher（model8）ckpt 路径")
    parser.add_argument("--epochs", type=int, default=1,
                        help="训练 epoch 数（gate_check 跑 1）")
    parser.add_argument("--gpu", default=None,
                        help="CUDA_VISIBLE_DEVICES（透传，优先用环境已有值）")
    args = parser.parse_args()

    if args.gpu is not None:
        os.environ["CUDA_VISIBLE_DEVICES"] = str(args.gpu)

    # KD 前置校验
    if args.kd and not args.teacher_ckpt:
        print("[RX-GATE] --kd given but --teacher-ckpt missing", file=sys.stderr)
        sys.exit(1)

    model, cfg, gate_passed = _smoke_and_gate(args)
    if not gate_passed:
        print("[RX-GATE] gate=FAIL —— 不进入训练（检查 I/O shape / model 名 / cfg 维度）",
              file=sys.stderr)
        sys.exit(1)

    # =====================================================================
    # <<<TODO: 用户训练循环插入点>>>
    # 把已建好的 model 注入你的训练循环。按 utils/__USER_TRAIN_MODULE__.py 的 API 选一：
    #
    #   (a) 暴露 callable：
    #       __USER_TRAIN_MODULE__.main(args)
    #       或 __USER_TRAIN_MODULE__.run_training(model=model, epochs=args.epochs)
    #
    #   (b) 模型实例化点在外层 —— monkeypatch 注入 get_model：
    #       import utils.__USER_TRAIN_MODULE__ as _ut
    #       _ut.get_model = lambda name, _cfg: get_model(args.model, cfg)
    #       _ut.main()
    #
    #   (c) KD：--kd 时用 kd_helper 包 loss（参考 kd_helper.py）：
    #       from kd_helper import KDHelper
    #       kd = KDHelper(teacher_build_fn=<model8 factory>,
    #                     teacher_ckpt=args.teacher_ckpt,
    #                     student_hook_names=model.feature_hook_names(),
    #                     device="cuda")
    #       # 训练步里：loss = kd(model, x, task_loss_fn, y)
    #
    # 适配 agent（执行 rx-sweep skill 的 agent）会按你的脚本结构填这里。
    # 占位实现：最小 forward+backward，打印 [RESULT] 行——让 gate_check 能验前向+反向通。
    # =====================================================================
    print("[RX-GATE] TODO: 用户训练循环未接线 —— 跑占位 forward+backward 验链路",
          file=sys.stderr, flush=True)
    optim = torch.optim.SGD(model.parameters(), lr=1e-3)
    x = torch.zeros(*cfg.io_shape, dtype=torch.float32)
    y_target = torch.zeros(*cfg.io_shape, dtype=torch.float32)
    model.train()
    out = model(x)
    loss = ((out - y_target) ** 2).mean()
    loss.backward()
    optim.step()
    print(f"[RESULT] model={args.model} step_loss={loss.item():.6f} "
          f"epochs={args.epochs} status=PLACEHOLDER", flush=True)


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# 逻辑
# ---------------------------------------------------------------------------

def _find_train_py(project_root: Path, train_py_hint: str | None) -> Path:
    """定位 train.py：用 hint 或扫 project_root（含一级子目录）。fail loud。"""
    if train_py_hint:
        p = Path(train_py_hint)
        if not p.is_absolute():
            p = project_root / p
        if not p.is_file():
            _fail(f"--train-py 不存在: {p}")
        return p.resolve()

    cand = project_root / "train.py"
    if cand.is_file():
        return cand.resolve()

    hits = sorted(project_root.glob("*/train.py"))
    if len(hits) == 1:
        return hits[0].resolve()
    if not hits:
        _fail(f"在 {project_root} 找不到 train.py（用 --train-py 指定入口）")
    _fail(f"多个 train.py 候选，用 --train-py 指定: {[str(h) for h in hits]}")


def _detect_utils_modules(train_py: Path) -> list[str]:
    """解析 train.py，返回它 import 的 utils/ 模块名列表（去重保序）。

    fail loud：未 import utils → SystemExit。
    """
    src = train_py.read_text(encoding="utf-8", errors="replace")
    candidates = []
    for m in _UTILS_IMPORT_RE.finditer(src):
        sub = m.group(1) or m.group(3)      # from utils.<sub> / import utils.<sub>
        imported = m.group(2)               # from utils import <name>
        if sub:
            candidates.append(sub)
        elif imported and imported != "utils":
            candidates.append(imported)
    # 去重保序
    seen = set()
    unique = []
    for c in candidates:
        if c not in seen:
            seen.add(c)
            unique.append(c)
    if not unique:
        _fail(
            f"{train_py} 未 import utils/ 下的训练脚本 —— "
            "确认入口结构（参考 adaptation-guide.md），或走方式 B 手工适配"
        )
    return unique


def _pick_train_module(modules: list[str]) -> str:
    """多个候选时优先名字含 'train' 的；否则取第一个。"""
    for m in modules:
        if "train" in m.lower():
            return m
    return modules[0]


def _render_runner(user_train_module: str) -> str:
    """填模板：注入用户训练脚本的 import 行。"""
    user_import = f"import utils.{user_train_module} as {user_train_module}"
    return (
        _RUNNER_TEMPLATE
        .replace("__USER_TRAIN_IMPORT__", user_import)
        .replace("__USER_TRAIN_MODULE__", user_train_module)
    )


def _fail(msg: str) -> None:
    """fail loud：stderr + 非零退出。"""
    print(f"adapt_project: {msg}", file=sys.stderr)
    sys.exit(2)


def main() -> int:
    ap = argparse.ArgumentParser(description="rx-sweep 适配脚本（方式 A：固化包装器）")
    ap.add_argument("--project-root", required=True, help="用户训练工程根目录")
    ap.add_argument("--train-py", default=None, help="train.py 路径（默认自动扫）")
    ap.add_argument("--dry-run", action="store_true",
                    help="只打印会生成的 rx_runner.py 内容，不写盘")
    args = ap.parse_args()

    project_root = Path(args.project_root).resolve()
    if not project_root.is_dir():
        _fail(f"--project-root 不是目录: {project_root}")

    train_py = _find_train_py(project_root, args.train_py)
    utils_modules = _detect_utils_modules(train_py)
    user_train_module = _pick_train_module(utils_modules)

    # 打印找到的训练脚本路径（任务要求，供适配 agent 确认）
    utils_dir = train_py.parent / "utils"
    print(f"TRAIN_PY: {train_py}")
    print(f"UTILS_TRAIN_MODULE: {user_train_module}")
    print(f"UTILS_TRAIN_PATH: {utils_dir / (user_train_module + '.py')}")
    if len(utils_modules) > 1:
        print(f"UTILS_OTHER_CANDIDATES: {utils_modules}")

    runner_src = _render_runner(user_train_module)

    if args.dry_run:
        print("=== rx_runner.py (dry-run) ===")
        print(runner_src)
        print("=== end ===")
        print("DRYRUN")
        return 0

    runner_path = project_root / "rx_runner.py"
    # 幂等：重跑覆盖，旧版 backup .bak
    if runner_path.is_file():
        bak = runner_path.with_suffix(".py.bak")
        shutil.copy2(runner_path, bak)
        print(f"BACKUP: {bak}")

    runner_path.write_text(runner_src, encoding="utf-8")
    print(f"ADAPTED: {runner_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
