#!/usr/bin/env python3
"""gen_export_onnx.py — generate the per-project export_onnx.py (artifacts root).

Reads the model construction facts recorded in contracts.json and EMITS a
standalone deterministic export script. This generator never imports user
code; the generated script does, at run time, under the shadow injection
header (the run wrapper supplies it — see render_run.sh).

Pinned export semantics (baseline and variants must export from the same
mold or their profiles are incomparable):
    - static shapes only (dynamic_axes forbidden / empty)
    - opset 17
    - fixed-seed dummy inputs
    - do_constant_folding=True

contracts.json model_facts schema consumed here:
    "model_facts": {
      "module": "pkg.model",          # resolved through the injection header
      "factory": "build_model",       # callable or class name in that module
      "args": [...], "kwargs": {...},
      "dummy_inputs": [{"name": "x", "shape": [1, 8], "dtype": "float32"}]
    }

stdout: {"script": path, "sha256": ...} — the sha is recorded into
contracts.json by the caller, so a regenerated/drifted export script is
detectable later.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

TEMPLATE = '''#!/usr/bin/env python3
"""export_onnx.py — GENERATED by gen_export_onnx.py from contracts.json.

Deterministic export for this project's model: static shapes, opset 17,
fixed-seed dummy inputs, constant folding on. Run under the shadow injection
header (the rendered run wrapper exports ORCA_SHADOW_DIR / ORCA_SHADOW_PKGS /
PYTHONPATH before invoking this script with the same interpreter).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import torch

MODEL_FACTS = json.loads(r"""
__MODEL_FACTS_JSON__
""")


def make_dummy(spec: dict, seed: int) -> torch.Tensor:
    torch.manual_seed(seed)
    shape = [int(d) for d in spec["shape"]]
    dtype_map = {
        "float32": torch.float32, "float64": torch.float64,
        "int64": torch.int64, "int32": torch.int32, "bool": torch.bool,
    }
    dtype = dtype_map[spec.get("dtype", "float32")]
    if dtype.is_floating_point:
        return torch.randn(shape, dtype=dtype)
    return torch.zeros(shape, dtype=dtype)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(Path(__file__).resolve().parent / "model.onnx"))
    ap.add_argument("--seed", type=int, default=0)
    ns = ap.parse_args()

    import importlib
    mod = importlib.import_module(MODEL_FACTS["module"])
    factory = getattr(mod, MODEL_FACTS["factory"])
    model = factory(*MODEL_FACTS.get("args", []), **MODEL_FACTS.get("kwargs", {}))
    if not isinstance(model, torch.nn.Module):
        model = model.model  # factory namespace holding .model
    model.eval()

    inputs = [make_dummy(spec, ns.seed + i)
              for i, spec in enumerate(MODEL_FACTS["dummy_inputs"])]
    input_names = [spec["name"] for spec in MODEL_FACTS["dummy_inputs"]]

    out = Path(ns.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    torch.onnx.export(
        model,
        tuple(inputs) if len(inputs) != 1 else inputs[0],
        str(out),
        input_names=input_names,
        output_names=["output"],
        opset_version=17,
        do_constant_folding=True,
        dynamic_axes=None,
    )
    print(json.dumps({"exported": str(out.resolve()), "opset": 17}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def generate(contracts_path: Path, out_dir: Path) -> dict:
    contracts = json.loads(contracts_path.read_text(encoding="utf-8"))
    facts = contracts.get("model_facts")
    if not isinstance(facts, dict):
        raise ValueError(f"{contracts_path} has no 'model_facts' object")
    for field in ("module", "factory", "dummy_inputs"):
        if field not in facts:
            raise ValueError(f"model_facts.{field} missing in {contracts_path}")
    for spec in facts["dummy_inputs"]:
        if "name" not in spec or "shape" not in spec:
            raise ValueError(f"dummy_inputs entry missing name/shape: {spec}")
    if any(spec.get("dynamic_axes") for spec in facts["dummy_inputs"]):
        raise ValueError("dynamic_axes forbidden — export must be static-shape")

    script = TEMPLATE.replace("__MODEL_FACTS_JSON__",
                               json.dumps(facts, indent=2))
    out = out_dir / "export_onnx.py"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(script, encoding="utf-8")
    return {"script": str(out.resolve()),
            "sha256": hashlib.sha256(out.read_bytes()).hexdigest()}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--contracts", required=True)
    ap.add_argument("--out-dir", required=True, help="artifacts root")
    ns = ap.parse_args()
    try:
        result = generate(Path(ns.contracts), Path(ns.out_dir))
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as exc:
        print(f"gen_export_onnx: FAIL {type(exc).__name__}: {exc}", file=sys.stderr)
        return 2
    print(json.dumps(result))
    return 0


if __name__ == "__main__":
    sys.exit(main())
