// types/events.ts —— **AUTO-GENERATED by scripts/gen_events_ts.py. DO NOT EDIT.**
//
// Source of truth: orca/schema/event.py EventType Literal (web-shell-v2 SPEC §0 D1).
// Drift guard: tests/iface/web/test_events_ts_drift.py 断言两边集合严格相等。
//
// 改后端 EventType → 跑 `python scripts/gen_events_ts.py`（package.json prebuild
// 已 wired）。前端派生类型（WorkflowStatus/NodeStatus/GateState/...）见 ./store-types.ts。


export type EventType =
  | "workflow_started"
  | "workflow_completed"
  | "workflow_failed"
  | "workflow_cancelled"
  | "node_started"
  | "node_completed"
  | "node_failed"
  | "node_skipped"
  | "agent_message"
  | "agent_thinking"
  | "agent_tool_call"
  | "agent_tool_result"
  | "agent_usage"
  | "agent_step_started"
  | "route_taken"
  | "foreach_started"
  | "foreach_item_started"
  | "foreach_item_completed"
  | "foreach_completed"
  | "human_decision_requested"
  | "human_decision_resolved"
  | "interrupt_requested"
  | "interrupt_resolved"
  | "prompt_rendered"
  | "workflow_resumed"
  | "retry_started"
  | "retry_succeeded"
  | "retry_exhausted"
  | "wait_started"
  | "wait_completed"
  | "validator_started"
  | "validator_passed"
  | "validator_failed"
  | "dialog_started"
  | "dialog_message"
  | "dialog_ended"
  | "custom"
  | "error"
  | "unknown_event";

export interface WebEvent {
  /** 全局单调递增（不变量；对齐 Event.seq）。 */
  seq: number;
  type: EventType;
  /** epoch 秒（对齐 Event.timestamp）。 */
  timestamp: number;
  /** 哪个 node 产出；workflow 级为 null。 */
  node: string | null;
  /** 哪次 agent 调用（独立 context）；workflow/node 级生命周期可为 null。 */
  session_id: string | null;
  /** 各 type 特定 payload（schema 不校验各 type 内部字段）。 */
  data: Record<string, unknown>;
  /** WS 推送时 ws_handler._pump 注入的来源 run 标签；REST /events 返回无此字段。 */
  run_id?: string;
}
