#!/usr/bin/env python3
"""gen_events_ts.py —— Web Shell v2 D1 codegen（SPEC §0 D1 / §3.2）。

把 ``orca/schema/event.py`` 的 ``EventType`` Literal 联合体的成员逐字同步到前端
``orca/iface/web/frontend/src/types/events.ts``，根治 21↔39 漂移。

生成物（仅两块，**手动不可编辑**）：
  1. ``EventType`` 联合体（39 个字面量，逐字来自 Python Literal）
  2. ``WebEvent`` 接口（镜像 ``Event`` BaseModel：seq/type/timestamp/node/session_id/data，
     + ``run_id?: string`` WS 标签字段，由 ws_handler._pump 注入）

其余前端派生类型（WorkflowStatus / NodeStatus / GateState / RunMeta / WsClientMessage）
**不在生成范围**——它们是前端派生而非后端契约，放在同目录 ``store-types.ts``，避免生成物
被手改污染。

用法::

    python scripts/gen_events_ts.py            # 写盘
    python scripts/gen_events_ts.py --check    # 仅校验，不写盘；drift 退出码 1

CI / 测试再加一道 backstop：``tests/iface/web/test_events_ts_drift.py`` 用
``typing.get_args(EventType)`` 与正则解析 events.ts 的 EventType 联合体成员集合
做严格相等断言（fail loud）。

依赖单向：仅依赖 ``orca.schema.event``（schema 层），不反向。
"""

from __future__ import annotations

import argparse
import io
import re
import sys
import textwrap
import typing
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EVENT_PY = REPO_ROOT / "orca" / "schema" / "event.py"
EVENTS_TS = (
    REPO_ROOT / "orca" / "iface" / "web" / "frontend" / "src" / "types" / "events.ts"
)

HEADER = """\
// types/events.ts —— **AUTO-GENERATED by scripts/gen_events_ts.py. DO NOT EDIT.**
//
// Source of truth: orca/schema/event.py EventType Literal (web-shell-v2 SPEC §0 D1).
// Drift guard: tests/iface/web/test_events_ts_drift.py 断言两边集合严格相等。
//
// 改后端 EventType → 跑 `python scripts/gen_events_ts.py`（package.json prebuild
// 已 wired）。前端派生类型（WorkflowStatus/NodeStatus/GateState/...）见 ./store-types.ts。

"""


def _extract_event_type_literal() -> tuple[str, ...]:
    """从 event.py 取 EventType Literal 的成员（顺序保留）。

    直接 import 取 typing.get_args —— Literal 顺序就是源码声明顺序，与 pytest drift
    guard 共享同一读取路径（单一真相）。
    """
    sys.path.insert(0, str(REPO_ROOT))
    # 延迟 import：脚本是工具，不应在 module import 时强求 orca 包整体可加载。
    from orca.schema.event import EventType  # noqa: PLC0415

    args = typing.get_args(EventType)
    sys.path.pop(0)
    if not args:
        raise RuntimeError("EventType Literal 为空 —— event.py 解析异常")
    return args


def _render_event_type_union(members: tuple[str, ...]) -> str:
    """渲染 EventType 联合体（每行一个 ``| "name"``，对齐 TypeScript 风格）。"""
    lines = ["export type EventType ="]
    for m in members:
        lines.append(f'  | "{m}"')
    lines[-1] += ";"
    return "\n".join(lines)


def _render_web_event_interface() -> str:
    """渲染 WebEvent 接口（镜像 orca/schema/event.py Event BaseModel）。

    ``run_id?`` 字段：ws_handler._pump 在 model_dump 后注入（让前端区分来源 run），
    REST /events 返回无此字段，故 optional。
    """
    return textwrap.dedent(
        """\
        export interface WebEvent {
          /** 全局单调递增（不变量；对齐 Event.seq）。 */
          seq: number;
          type: EventType;
          /** epoch 秒（对齐 Event.timestamp）。 */
          timestamp: number;
          /** 哪个 node 产出；workflow 级为 null。 */
          node: string | null;
          /** 哪次 agent 调用（独立 context）；workflow/node 级生命周期可为 null。 */
          session_id: string | null;
          /** 各 type 特定 payload（schema 不校验各 type 内部字段）。 */
          data: Record<string, unknown>;
          /** WS 推送时 ws_handler._pump 注入的来源 run 标签；REST /events 返回无此字段。 */
          run_id?: string;
        }
        """
    )


def build_events_ts(members: tuple[str, ...]) -> str:
    """组装 events.ts 全文。"""
    buf = io.StringIO()
    buf.write(HEADER)
    buf.write("\n")
    buf.write(_render_event_type_union(members))
    buf.write("\n\n")
    buf.write(_render_web_event_interface())
    return buf.getvalue()


def _parse_generated_event_type(text: str) -> set[str]:
    """从 events.ts 文本反向解析 EventType 成员集合（drift --check 用）。"""
    block = re.search(r"export type EventType =\s*((?:\s*\| \"[a-z_]+\")+\s*);", text)
    if not block:
        raise RuntimeError("events.ts EventType 联合体未匹配")
    return set(re.findall(r'\|"([a-z_]+)"', block.group(1).replace(" ", "")))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="只校验不写盘：events.ts 与 EventType 不一致则退出码 1",
    )
    args = parser.parse_args()

    members = _extract_event_type_literal()
    expected_text = build_events_ts(members)

    if args.check:
        if not EVENTS_TS.exists():
            print(f"[codegen] 缺失 {EVENTS_TS}（请先跑 gen_events_ts.py）", file=sys.stderr)
            return 1
        actual = EVENTS_TS.read_text(encoding="utf-8")
        actual_set = _parse_generated_event_type(actual)
        expected_set = set(members)
        if actual_set != expected_set:
            missing = expected_set - actual_set
            extra = actual_set - expected_set
            print(
                f"[codegen] events.ts EventType 漂移：missing={sorted(missing)} "
                f"extra={sorted(extra)}",
                file=sys.stderr,
            )
            return 1
        if actual.strip() != expected_text.strip():
            print(
                "[codegen] events.ts 内容与 EventType 不同步（注释/格式漂移），请重跑 gen_events_ts.py",
                file=sys.stderr,
            )
            return 1
        print(f"[codegen] OK：events.ts EventType 同步 ({len(members)} 个)")
        return 0

    EVENTS_TS.parent.mkdir(parents=True, exist_ok=True)
    EVENTS_TS.write_text(expected_text, encoding="utf-8")
    print(f"[codegen] 写入 {EVENTS_TS.relative_to(REPO_ROOT)} ({len(members)} 个 EventType)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
