"""train_pipeline.py — KD-NAS unified training script (teacher + distill + eval modes).

Generated by the ``kd-train-script`` agent.  Self-contained: copies the user's
loss / dataloader / optimizer / eval-metric logic inline (never imports the
user's project), loads teacher/student models **by path** via
:mod:`importlib.util`, and runs on a single device (no distributed
data-parallel launch, no torchrun, no architecture sampling — KD-NAS uses a
``ThreadPoolExecutor`` round-robin pool at the workflow level, not inside the
training script).

Three modes
-----------
* ``--mode teacher``   — train a teacher with pure ``user_task_loss``, save a
  checkpoint consumable by ``teacher_setup`` (state_dict + build_cfg).
* ``--mode distill``   — train a student with ``user_task_loss`` + KD loss
  (assembled via :func:`kd.compose.build_kd_loss`), save the student ckpt.
* ``--mode eval``      — load a student ckpt, run the user's eval metric
  (discovered by the agent from the user repo's eval script, e.g.
  ``test_student.py``), and emit the accuracy protocol consumed by
  ``train_pool``. Read-only: no checkpoint is written; this mode replaces the
  old ``measure_student --eval_command`` path.

When the ``{{USER_TRAIN_MODULE}}`` / ``{{USER_EVAL_MODULE}}`` placeholders are
left unexpanded the script runs on placeholder fallbacks (dummy MSE loss +
random re-iterable loader + dummy NMSE eval) so it is smoke-testable
standalone before the agent specialises it.

Generation contract (verifier cross-checks this)
------------------------------------------------
* Stdout keys (teacher mode): ``TEACHER_CKPT: <path>`` + ``TASK_LOSS_FINAL: <float>``
* Stdout keys (distill mode): ``STUDENT_CKPT: <path>`` + ``KD_LOSS_FINAL: <float>``
  + ``KD_PROXY_MSE: <float>``
* Stdout keys (eval mode): ``STUDENT_ACCURACY: <float>`` +
  ``STUDENT_ACCURACY_KIND: <nmse|mse|ber|snr|acc>`` + ``MET_ACCURACY: <bool>``
  + ``ACCURACY_CONFIDENCE: high|low`` (no ckpt written — read-only evaluation).
* Teacher ckpt schema: ``{state_dict, build_cfg, variant_id, epochs, final_loss, mode}``
* Student ckpt schema: ``{student_state_dict, variant_id, student_cfg, kd_config,
  epochs, proxy_mse, mode}``
"""

from __future__ import annotations

import argparse
import importlib
import importlib.util
import json
import math
import os
import sys
from pathlib import Path
from typing import Callable, Iterator, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

# ---------------------------------------------------------------------------
# sys.path bootstrap for ``kd/`` imports + optional user project root.
#
# The generated script may live in ``<output_dir>`` (not ``_kd_scripts/``),
# so prefer ``ORCA_KD_SCRIPTS_DIR`` (injected by the kd-train workflow) and
# fall back to this file's own directory so the template runs standalone.
# ---------------------------------------------------------------------------
_KD_SCRIPTS_DIR = Path(
    os.environ.get("ORCA_KD_SCRIPTS_DIR", Path(__file__).resolve().parent)
)
if str(_KD_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_KD_SCRIPTS_DIR))

_PROJECT_ROOT = os.environ.get("ORCA_PROJECT_ROOT", "")
if _PROJECT_ROOT and _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

# ===========================================================================
# USER PLACEHOLDERS — kd-train-script agent replaces these when generating a
# project-specific train_pipeline.py.  Leaving them as ``{{...}}`` strings
# keeps the template self-runnable via the placeholder fallback below.
# ===========================================================================
USER_TRAIN_MODULE = "{{USER_TRAIN_MODULE}}"   # e.g. "train" or "/abs/path/train.py"
USER_LOSS_FN = "{{USER_LOSS_FN}}"             # e.g. "compute_loss"
USER_EVAL_MODULE = "{{USER_EVAL_MODULE}}"     # e.g. "test_student" or "/abs/path/test_student.py"
USER_EVAL_FN = "{{USER_EVAL_FN}}"             # e.g. "evaluate" -> (value: float, kind: str)


# ---------------------------------------------------------------------------
# Placeholder fallbacks — keep the template runnable before specialisation.
# ---------------------------------------------------------------------------
def _placeholder_user_loss(s_out: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
    """Default user task loss — MSE to target ``y`` (same shape as student output)."""
    return F.mse_loss(s_out, y)


class _PlaceholderDataLoader:
    """Re-iterable random (x, y) batch generator for smoke tests.

    Mirrors the ``examples/kd-nas-demo/train.py`` ``_RandomDataLoader`` contract:
    each ``iter()`` yields a fresh stream of ``n_batches`` random batches with
    shape aligned to ``DUMMY_INPUT``.  Re-iterable so multi-epoch training
    doesn't exhaust after the first epoch.
    """

    def __init__(
        self,
        batch_size: int = 4,
        n_batches: int = 8,
        shape: Tuple[int, ...] = (1, 4, 48, 64, 1),
    ) -> None:
        self.batch_size = batch_size
        self.n_batches = n_batches
        self.shape = shape

    def __iter__(self) -> Iterator[Tuple[torch.Tensor, torch.Tensor]]:
        inner = tuple(self.shape[1:])
        for _ in range(self.n_batches):
            x = torch.randn(self.batch_size, *inner)
            y = torch.randn(self.batch_size, *inner)
            yield x, y

    def __len__(self) -> int:
        return self.n_batches


def _placeholder_build_dataloader(batch_size: int = 4) -> _PlaceholderDataLoader:
    return _PlaceholderDataLoader(batch_size=batch_size)


def _placeholder_user_eval(student: nn.Module, device) -> tuple[float, str]:
    """Default user eval metric — NMSE on one random batch (mirrors the
    placeholder dataloader's inner shape). Returns ``(nmse, "nmse")`` so the
    eval mode is smoke-testable before the agent specialises it.

    The agent replaces this with the user's real eval metric (ported from the
    user repo's eval script) — same signature ``(student, device) -> (value, kind)``.
    """
    inner = (4, 48, 64, 1)  # demo-aligned with _PlaceholderDataLoader.shape
    x = torch.randn(1, *inner).to(device)
    y = torch.randn(1, *inner).to(device)
    student.eval()
    with torch.no_grad():
        out = student(x)
    out = out.reshape_as(y)
    num = float(torch.sum((out - y) ** 2).item())
    den = float(torch.sum(y ** 2).item()) + 1e-12
    return num / den, "nmse"


def _load_user_train() -> Tuple[Callable, Callable]:
    """Resolve user task loss + dataloader builders.

    Returns ``(loss_fn, build_dataloader)``.  When the placeholders are
    unexpanded (``{{...}}``), returns placeholder fallbacks so the template
    runs end-to-end without the user's code present.  Otherwise imports the
    user's train module by path or module name.

    ``build_dataloader`` may be absent in the user module — the KD-NAS user
    contract only guarantees ``compute_loss``; in that case fall back to the
    placeholder loader and emit a stderr note (fail loud on loss, lenient on
    loader with explicit fallback).
    """
    if USER_TRAIN_MODULE.startswith("{{"):
        return _placeholder_user_loss, _placeholder_build_dataloader

    if os.path.isfile(USER_TRAIN_MODULE):
        spec = importlib.util.spec_from_file_location("_user_train", USER_TRAIN_MODULE)
        if spec is None or spec.loader is None:
            raise ImportError(f"cannot construct import spec for {USER_TRAIN_MODULE}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    else:
        module = importlib.import_module(USER_TRAIN_MODULE)

    if not hasattr(module, USER_LOSS_FN):
        raise AttributeError(
            f"user train module {USER_TRAIN_MODULE!r} has no loss fn {USER_LOSS_FN!r}"
        )
    loss_fn = getattr(module, USER_LOSS_FN)
    build_dl = getattr(module, "build_dataloader", None)
    if build_dl is None:
        # KD-NAS user contract does not require build_dataloader — explicit fallback.
        print(
            f"[train_pipeline] NOTE: user module {USER_TRAIN_MODULE!r} has no "
            f"build_dataloader; using placeholder random loader.",
            file=sys.stderr,
        )
        build_dl = _placeholder_build_dataloader
    return loss_fn, build_dl


def _load_user_eval() -> Callable:
    """Resolve the user eval metric function.

    Returns a callable ``fn(student: nn.Module, device) -> (value: float,
    kind: str)``. When the placeholder is unexpanded (``{{...}}``), returns the
    placeholder eval fn so the template runs end-to-end. Otherwise imports the
    user's eval module (discovered from the user repo's eval script, e.g.
    ``test_student.py``) by path or module name and resolves ``USER_EVAL_FN``.

    The agent ports the user's eval logic (data loading + metric computation)
    into this callable — it must be self-contained (no user-project imports).
    When the user's eval script does not expose a matching-signature function,
    the agent inlines an ``evaluate_student`` helper into the generated script
    and points ``USER_EVAL_MODULE``/``USER_EVAL_FN`` at it.
    """
    if USER_EVAL_MODULE.startswith("{{"):
        return _placeholder_user_eval

    if os.path.isfile(USER_EVAL_MODULE):
        spec = importlib.util.spec_from_file_location("_user_eval", USER_EVAL_MODULE)
        if spec is None or spec.loader is None:
            raise ImportError(f"cannot construct import spec for {USER_EVAL_MODULE}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    else:
        module = importlib.import_module(USER_EVAL_MODULE)

    if not hasattr(module, USER_EVAL_FN):
        raise AttributeError(
            f"user eval module {USER_EVAL_MODULE!r} has no eval fn {USER_EVAL_FN!r}"
        )
    return getattr(module, USER_EVAL_FN)


# ---------------------------------------------------------------------------
# Model load by path (KD-NAS teacher/student contract: build_model + DUMMY_INPUT).
# ---------------------------------------------------------------------------
def _load_model_by_path(model_path: str, build_fn: str, cfg: dict) -> nn.Module:
    """Import a model ``.py`` by absolute path and call ``build_fn(**cfg)``.

    Inserts the model file's directory into ``sys.path`` so shared-block
    imports (e.g. ``from _model8_blocks import ...``) resolve for KD-NAS
    variants living in ``knowledge_base/families/receiver/``.  Re-registers
    the module in ``sys.modules`` so downstream ``importlib`` hits cache.
    """
    model_path = os.path.abspath(model_path)
    if not os.path.isfile(model_path):
        raise FileNotFoundError(f"model_path not found: {model_path}")
    model_dir = os.path.dirname(model_path)
    if model_dir not in sys.path:
        sys.path.insert(0, model_dir)
    module_name = Path(model_path).stem
    spec = importlib.util.spec_from_file_location(module_name, model_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot construct import spec for {model_path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = mod
    spec.loader.exec_module(mod)
    if not hasattr(mod, build_fn):
        raise AttributeError(
            f"{model_path} has no build fn {build_fn!r}; available: "
            f"{[n for n in dir(mod) if not n.startswith('_')]}"
        )
    return getattr(mod, build_fn)(**cfg)


def _resolve_device(name: str) -> torch.device:
    if name == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    return torch.device(name)


def _build_dataloader(build_dataloader: Callable, batch_size: int):
    """Call ``build_dataloader()``; fall back to ``build_dataloader(batch_size=)``.

    The user contract permits either signature; try the no-arg form first
    (matches ``examples/kd-nas-demo/train.py``) and gracefully accept the
    kwargs form.
    """
    try:
        return build_dataloader()
    except TypeError:
        return build_dataloader(batch_size=batch_size)


def _make_live_push(variant_id: str, mode: str):
    """Per-epoch live chart push (best-effort, never kills the training loop).

    Mirrors ``train_adapter_template._make_live_push``: lazy import
    ``orca.chart.render_chart``; on any failure (import error, push error)
    degrade to a no-op or stderr warning.  Same ``label``+``title`` re-push
    = refresh semantics (dedup).
    """
    try:
        from orca.chart import render_chart  # type: ignore
    except Exception:
        render_chart = None  # type: ignore
    label = f"kd-{mode}-{variant_id}"
    title = f"{mode} loss — {variant_id}"

    def push(curve: list) -> None:
        if render_chart is None:
            return
        try:
            render_chart(
                chart_type="line",
                data=curve,
                label=label,
                title=title,
                x="epoch",
                y="loss",
                x_label="epoch",
                y_label="loss（越低越好）",
                caption=f"{mode} training loss per-epoch (variant={variant_id})",
            )
        except Exception as e:  # best-effort sidecar: never abort training
            print(
                f"[train_pipeline:{mode}] WARN: render_chart failed "
                f"(ignored): {type(e).__name__}: {e}",
                file=sys.stderr,
            )

    return push


def _maybe_bootstrap_env(env_anchor: str) -> None:
    """best-effort ORCA env bootstrap from per-run artifacts anchor.

    Prevents the agent-spawned bash losing ``ORCA_CHART_SOCK`` (which would
    make live chart pushes silently no-op).  Failure is non-fatal — only a
    stderr warning is emitted.
    """
    if not env_anchor:
        return
    try:
        from orca.chart._env import load_run_env_from_artifacts  # type: ignore

        load_run_env_from_artifacts(env_anchor)
    except Exception as e:
        print(
            f"[train_pipeline] WARN: env bootstrap failed "
            f"(live chart may not push): {type(e).__name__}: {e}",
            file=sys.stderr,
        )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="KD-NAS unified training pipeline (teacher + distill modes)"
    )
    # --- mode + shared runtime -------------------------------------------
    p.add_argument(
        "--mode",
        required=True,
        choices=["teacher", "distill", "eval"],
        help="mode: teacher (task_loss only) / distill (task_loss + KD) / eval (read-only metric)",
    )
    p.add_argument("--out_ckpt", required=True, help="output checkpoint path")
    p.add_argument("--epochs", type=int, default=3, help="training epochs")
    p.add_argument("--lr", type=float, default=1e-3, help="learning rate")
    p.add_argument("--batch_size", type=int, default=4, help="batch size")
    p.add_argument(
        "--device",
        default="auto",
        help="cuda / cpu / auto (default auto: cuda if available else cpu)",
    )
    p.add_argument("--seed", type=int, default=0, help="reproducibility seed")
    p.add_argument(
        "--variant_id",
        default="model",
        help="variant id used in chart label/title and ckpt metadata",
    )

    # --- model loading (shared; teacher uses --model_path, distill uses --student_model_path)
    p.add_argument(
        "--build_fn", default="build_model", help="build function name in the model module"
    )
    p.add_argument(
        "--build_cfg",
        default="{}",
        help="JSON dict passed to build_model(**cfg) (teacher build_cfg / student_cfg)",
    )

    # --- teacher mode ----------------------------------------------------
    p.add_argument(
        "--model_path",
        default=None,
        help="[teacher mode] teacher model .py path (importlib-loaded by path)",
    )

    # --- distill mode ----------------------------------------------------
    p.add_argument(
        "--student_model_path",
        default=None,
        help="[distill mode] student model .py path (KD-NAS variant in KB)",
    )
    p.add_argument(
        "--teacher_cache",
        default=None,
        help="[distill mode] teacher_cache.pt path (produced by teacher_setup.py)",
    )
    p.add_argument(
        "--kd_config",
        default='{"kd_losses": [], "weights": {}}',
        help="[distill mode] JSON kd_config for kd.compose.build_kd_loss",
    )

    # --- user train.py injection ----------------------------------------
    p.add_argument(
        "--user_train_import",
        default=None,
        help="user train.py path or module (overrides USER_TRAIN_MODULE placeholder)",
    )
    p.add_argument(
        "--user_loss_fn",
        default=None,
        help="user loss fn name in the train module (overrides USER_LOSS_FN placeholder)",
    )
    p.add_argument(
        "--user_eval_import",
        default=None,
        help="user eval module path/name (overrides USER_EVAL_MODULE placeholder)",
    )
    p.add_argument(
        "--user_eval_fn",
        default=None,
        help="user eval fn name -> (value, kind) (overrides USER_EVAL_FN placeholder)",
    )

    # --- eval mode -------------------------------------------------------
    p.add_argument(
        "--student_ckpt",
        default=None,
        help="[eval mode] student checkpoint to load (student_state_dict consumed)",
    )
    p.add_argument(
        "--accuracy_baseline",
        default=None,
        help="[eval mode] absolute accuracy baseline (user-provided)",
    )
    p.add_argument(
        "--accuracy_baseline_kind",
        default=None,
        help="[eval mode] nmse/mse/ber/db (lower better) | snr/acc (higher better)",
    )

    p.add_argument(
        "--project_root",
        default=None,
        help="user project root (for user-side from-X-import-Y); added to sys.path",
    )

    # --- env -------------------------------------------------------------
    p.add_argument(
        "--env_anchor",
        default="",
        help="per-run $ORCA_ARTIFACTS_DIR anchor for env bootstrap",
    )
    return p.parse_args()


# ===========================================================================
# Teacher mode — pure task_loss training, save ckpt for teacher_setup.
# ===========================================================================
def run_teacher_mode(args: argparse.Namespace, user_loss: Callable, build_dataloader: Callable) -> int:
    if not args.model_path:
        raise SystemExit("[teacher mode] --model_path is required")

    cfg = json.loads(args.build_cfg)
    torch.manual_seed(args.seed)
    device = _resolve_device(args.device)

    teacher = _load_model_by_path(args.model_path, args.build_fn, cfg).to(device).train()

    # TODO(kd-train-script): when the user's train.py defines an optimizer / scheduler
    # builder, port it here verbatim (replace Adam + no-scheduler fallback) and
    # annotate the fallback explicitly.  Default: Adam + no scheduler.
    optimizer = torch.optim.Adam(teacher.parameters(), lr=args.lr)
    # NOTE: no scheduler in fallback — KD-NAS teacher is a one-shot soft-label
    # source and the user's original scheduler (if any) should be ported, not invented.

    dl = _build_dataloader(build_dataloader, args.batch_size)

    live_push = _make_live_push(args.variant_id, "teacher")
    loss_curve: list = []
    last_avg = float("nan")
    for epoch in range(args.epochs):
        teacher.train()
        epoch_loss = 0.0
        n_batches = 0
        for x, y in iter(dl):
            x = x.to(device)
            y = y.to(device)
            out = teacher(x)
            loss = user_loss(out, y)
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()
            epoch_loss += float(loss.detach())
            n_batches += 1
        if n_batches == 0:
            print(
                f"[train_pipeline:teacher] epoch={epoch}: dataloader empty, stopping",
                file=sys.stderr,
            )
            break
        last_avg = epoch_loss / max(n_batches, 1)
        print(f"[train_pipeline:teacher] epoch={epoch} loss_avg={last_avg:.6f}", flush=True)
        loss_curve.append({"epoch": epoch, "loss": last_avg})
        live_push(loss_curve)

    if not math.isfinite(last_avg):
        # Dataloader produced zero batches across all epochs (e.g. user
        # build_dataloader returned an empty loader / one-shot generator that
        # exhausted in a prior step). Saving a NaN ckpt would silently
        # propagate NaN through teacher_setup → distill → proxy_mse with
        # returncode=0 — fail loud instead (CLAUDE.md Rule 12).
        raise SystemExit(
            "[teacher mode] no training batches were yielded (last_loss is NaN); "
            "aborting before ckpt save. Check build_dataloader() — must be "
            "re-iterable and yield at least one batch per epoch."
        )

    out_path = Path(args.out_ckpt)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "state_dict": teacher.state_dict(),
            "build_cfg": cfg,
            "variant_id": args.variant_id,
            "epochs": args.epochs,
            "final_loss": last_avg,
            "mode": "teacher",
        },
        out_path,
    )
    print(f"TEACHER_CKPT: {out_path}")
    print(f"TASK_LOSS_FINAL: {last_avg:.6f}")
    return 0


# ===========================================================================
# Distill mode — task_loss + KD composite, save student ckpt.
# ===========================================================================
def run_distill_mode(args: argparse.Namespace, user_loss: Callable, build_dataloader: Callable) -> int:
    if not args.student_model_path:
        raise SystemExit("[distill mode] --student_model_path is required")
    if not args.teacher_cache:
        raise SystemExit("[distill mode] --teacher_cache is required")

    # Lazy import so teacher-mode runs don't require ``kd/`` on sys.path.
    from kd.wrapper import KDStudentWrapper, TeacherCache
    from kd.compose import build_kd_loss
    from kd.ema import MeanTeacherEMA

    student_cfg = json.loads(args.build_cfg)
    kd_config = json.loads(args.kd_config)

    torch.manual_seed(args.seed)
    device = _resolve_device(args.device)

    # --- student --------------------------------------------------------
    student = _load_model_by_path(args.student_model_path, args.build_fn, student_cfg)
    hook_fn = getattr(student, "feature_hook_names", None)
    hook_names = list(hook_fn()) if callable(hook_fn) else []
    wrapper = KDStudentWrapper(student, hook_names).to(device)

    # --- teacher cache (resident in memory; frozen) --------------------
    teacher = TeacherCache.load(args.teacher_cache).to(device)

    # --- KD composite loss (owns OFD/FitNets adapters) -----------------
    kd_loss = build_kd_loss(user_loss, kd_config)

    # --- EMA (mean teacher) --------------------------------------------
    ema = None
    if kd_config.get("ema"):
        ema = MeanTeacherEMA(
            student, decay=float(kd_config.get("ema_decay", 0.999))
        ).to(device)

    # --- dataloader -----------------------------------------------------
    dl = _build_dataloader(build_dataloader, args.batch_size)

    # Materialise one batch so KD adapters (OFD/FitNets) can pre-build their
    # parameters *before* the optimizer is constructed (so they get registered).
    # Only x0 is needed (features drive adapter shapes); y0 is unused here.
    dl_iter = iter(dl)
    x0, _ = next(dl_iter)
    x0 = x0.to(device)

    wrapper.eval()
    with torch.no_grad():
        _, t_feats0 = teacher(x0)
        _, s_feats0 = wrapper(x0)
    wrapper.train()
    kd_loss.prepare(s_feats0, t_feats0)

    # --- optimizer ------------------------------------------------------
    # TODO(kd-train-script): port the user's optimizer / scheduler if present.
    # Default: Adam over student + KD adapter params, no scheduler.
    optimizer = torch.optim.Adam(
        list(wrapper.parameters()) + list(kd_loss.kd_parameters()),
        lr=args.lr,
    )

    # --- training loop --------------------------------------------------
    live_push = _make_live_push(args.variant_id, "distill")
    loss_curve: list = []
    last_avg = float("nan")
    for epoch in range(args.epochs):
        wrapper.train()
        epoch_loss = 0.0
        n_batches = 0
        for x, y in iter(dl):
            x = x.to(device)
            y = y.to(device)

            s_out, s_feats = wrapper(x)
            with torch.no_grad():
                t_out, t_feats = teacher(x)
            ema_out = ema(x) if ema is not None else None

            # kd_loss internally calls user_loss(s_out, y) and adds KD terms.
            loss = kd_loss(s_out, y, s_feats, t_out, t_feats, ema_out, epoch)

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()

            if ema is not None:
                ema.update(wrapper.student)

            epoch_loss += float(loss.detach())
            n_batches += 1

        if n_batches == 0:
            print(
                f"[train_pipeline:distill] epoch={epoch}: dataloader empty, stopping",
                file=sys.stderr,
            )
            break
        last_avg = epoch_loss / max(n_batches, 1)
        print(
            f"[train_pipeline:distill] epoch={epoch} kd_loss_avg={last_avg:.6f}",
            flush=True,
        )
        loss_curve.append({"epoch": epoch, "loss": last_avg})
        live_push(loss_curve)

    if not math.isfinite(last_avg):
        # See teacher mode for rationale: a NaN final loss means no batch was
        # processed — fail loud rather than silently emit a NaN ckpt.
        raise SystemExit(
            "[distill mode] no training batches were yielded (last_loss is NaN); "
            "aborting before ckpt save. Check build_dataloader() — must be "
            "re-iterable and yield at least one batch per epoch."
        )

    proxy_mse = _compute_proxy_mse(wrapper, teacher, dl, device)

    out_path = Path(args.out_ckpt)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "student_state_dict": wrapper.student.state_dict(),
            "variant_id": args.variant_id,
            "student_cfg": student_cfg,
            "kd_config": kd_config,
            "epochs": args.epochs,
            "proxy_mse": proxy_mse,
            "mode": "distill",
        },
        out_path,
    )
    print(f"STUDENT_CKPT: {out_path}")
    print(f"KD_LOSS_FINAL: {last_avg:.6f}")
    print(f"KD_PROXY_MSE: {proxy_mse:.6f}")
    return 0


# ===========================================================================
# Eval mode — load student ckpt, run user eval metric, emit accuracy protocol.
# Read-only: no checkpoint written. Replaces measure_student's accuracy path.
# ===========================================================================
def run_eval_mode(args: argparse.Namespace, user_eval: Callable) -> int:
    if not args.student_model_path:
        raise SystemExit("[eval mode] --student_model_path is required")
    if not args.student_ckpt:
        raise SystemExit("[eval mode] --student_ckpt is required")

    cfg = json.loads(args.build_cfg)
    device = _resolve_device(args.device)

    student = _load_model_by_path(args.student_model_path, args.build_fn, cfg).to(device)
    ck = torch.load(args.student_ckpt, map_location=device)
    if isinstance(ck, dict) and isinstance(ck.get("student_state_dict"), dict):
        sd = ck["student_state_dict"]            # distill ckpt key
    elif isinstance(ck, dict) and isinstance(ck.get("state_dict"), dict):
        sd = ck["state_dict"]                    # teacher / generic ckpt key
    elif isinstance(ck, dict):
        sd = ck                                  # bare state_dict dict (layer -> tensor)
    else:
        sd = ck
    missing, unexpected = student.load_state_dict(sd, strict=False)
    if missing:
        print(
            f"[train_pipeline:eval] WARN missing keys (top5): {list(missing)[:5]}",
            file=sys.stderr,
        )
    if unexpected:
        print(
            f"[train_pipeline:eval] WARN unexpected keys (top5): {list(unexpected)[:5]}",
            file=sys.stderr,
        )
    student.eval()

    # User eval metric (ported from the user repo's eval script): self-contained
    # data loading + metric computation -> (value, kind). A non-finite result must
    # surface loudly (mirrors _compute_proxy_mse fail-loud), never a silent 0.0.
    with torch.no_grad():
        value, kind = user_eval(student, device)
    if not math.isfinite(float(value)):
        raise SystemExit(
            f"[eval mode] user eval returned non-finite value={value}; aborting "
            "(a fake metric would mask a broken eval pipeline — CLAUDE.md Rule 12)."
        )

    # Direction + met judgment via kd_common.accuracy_direction (lazy import so
    # teacher/eval-only runs stay kd-free when _kd_scripts is off sys.path;
    # mirrors distill mode's lazy kd.wrapper import).
    confidence = "high"
    met = False
    if args.accuracy_baseline is not None and args.accuracy_baseline_kind:
        try:
            from kd_common import accuracy_direction  # type: ignore
            direction = accuracy_direction(args.accuracy_baseline_kind)
        except ImportError:
            direction = ""
        baseline = float(args.accuracy_baseline)
        if direction == "max":
            met = bool(value >= baseline)
        elif direction == "min":
            met = bool(value <= baseline)
        else:
            confidence = "low"
            print(
                f"[train_pipeline:eval] WARN: accuracy_baseline_kind="
                f"{args.accuracy_baseline_kind!r} unknown direction; "
                f"met_accuracy=false, confidence=low.",
                file=sys.stderr,
            )
    else:
        confidence = "low"
        print(
            "[train_pipeline:eval] WARN: --accuracy_baseline / "
            "--accuracy_baseline_kind not given; met_accuracy=false (low).",
            file=sys.stderr,
        )

    print(f"STUDENT_ACCURACY: {value}")
    print(f"STUDENT_ACCURACY_KIND: {kind}")
    print(f"MET_ACCURACY: {str(met).lower()}")
    print(f"ACCURACY_CONFIDENCE: {confidence}")
    return 0


@torch.no_grad()
def _compute_proxy_mse(wrapper, teacher, dataloader, device, max_batches: int = 3) -> float:
    """Soft MSE between student and teacher outputs — short-training proxy.

    Mirrors ``train_adapter_template._compute_proxy_mse``: capped at
    ``max_batches`` to bound cost; averages MSE over seen batches. Fails loud
    on an empty dataloader (returns no batch to average) rather than silently
    returning 0.0 — proxy_mse is a downstream-consumed signal and a fake 0.0
    would mask a broken pipeline (CLAUDE.md Rule 12).
    """
    wrapper.eval()
    total = 0.0
    seen = 0
    for x, _ in dataloader:
        x = x.to(device)
        s_out, _ = wrapper(x)
        t_out, _ = teacher(x)
        total += float(F.mse_loss(s_out, t_out).detach())
        seen += 1
        if seen >= max_batches:
            break
    if seen == 0:
        raise SystemExit(
            "_compute_proxy_mse: dataloader yielded no batch — cannot compute "
            "proxy MSE. Check that build_dataloader() is re-iterable."
        )
    return total / seen


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    args = parse_args()

    _maybe_bootstrap_env(args.env_anchor)

    if args.project_root and args.project_root not in sys.path:
        sys.path.insert(0, args.project_root)

    # Override placeholders if the CLI provided user module / loss fn, then
    # resolve once.  Both modes consume the same (loss_fn, build_dataloader).
    global USER_TRAIN_MODULE, USER_LOSS_FN, USER_EVAL_MODULE, USER_EVAL_FN
    if args.user_train_import:
        USER_TRAIN_MODULE = args.user_train_import
    if args.user_loss_fn:
        USER_LOSS_FN = args.user_loss_fn
    if args.user_eval_import:
        USER_EVAL_MODULE = args.user_eval_import
    if args.user_eval_fn:
        USER_EVAL_FN = args.user_eval_fn
    if args.mode == "eval":
        # eval mode is read-only: it needs only the user eval metric, not the
        # train loss/dataloader — resolve it independently so eval never depends
        # on train.py's compute_loss being importable.
        user_eval = _load_user_eval()
        return run_eval_mode(args, user_eval)

    user_loss, build_dataloader = _load_user_train()

    if args.mode == "teacher":
        return run_teacher_mode(args, user_loss, build_dataloader)
    return run_distill_mode(args, user_loss, build_dataloader)


if __name__ == "__main__":
    sys.exit(main())
